### ISSUE TITLE
CSS Files with Single Quotes

### ISSUE THREAD

**Issue by ShawnPavel** [NathanWalker/nativescript-ng2-fonticon#16]
I'm using the Material Design Iconic Font from [here](http://zavoloklom.github.io/material-design-iconic-font/icons.html) and had a bit of difficulty getting it to work.

It basically came down to the way the icon classes are defined in css. the material design icons are defined like this:
```css
.zmdi-floppy:before {
  content: '\f297';
}
```
whereas the font awesome icons are defined like this:
```css
.fa-floppy-o:before {
  content: "\f0c7";
}
```
The only difference is the single vs double quotes. With single quotes the icons will never show up and no errors are generated. This is because of the way javascript interprets the single quote compared to the double quote.
