### ISSUE TITLE
Can't run 4.2.0

### ISSUE THREAD

**Issue by Burgov** [NathanWalker/nativescript-ng2-fonticon#39]
Because of [this change](https://github.com/NathanWalker/nativescript-ngx-fonticon/commit/8fd8abb136d2442581832ebfb2a9cd0d3cfc53da#diff-473188db6183094c89c0e1fe2475a014R8), I'm not getting the following error:

```
TypeError: document.createElement is not a function
File: "file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/util/Immediate.js, line: 56, column: 68

StackTrace: 
    Frame: function:'ImmediateDefinition.canUseReadyStateChange', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/util/Immediate.js', line: 56, column: 69
    Frame: function:'ImmediateDefinition', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/util/Immediate.js', line: 30, column: 27
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/util/Immediate.js', line: 208, column: 21
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/scheduler/AsapAction.js', line: 7, column: 19
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/scheduler/asap.js', line: 2, column: 20
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/observable/SubscribeOnObservable.js', line: 8, column: 14
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/operators/subscribeOn.js', line: 2, column: 31
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/operator/subscribeOn.js', line: 2, column: 21
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/add/operator/subscribeOn.js', line: 3, column: 21
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/rxjs/Rx.js', line: 121, column: 1
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/nativescript-ngx-fonticon/services/fonticon.service.js', line: 5, column: 14
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/nativescript-ngx-fonticon/pipes/fonticon.pipe.js', line: 4, column: 26
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/tns_modules/nativescript-ngx-fonticon/nativescript-ngx-fonticon.js', line: 7, column: 23
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/app.module.js', line: 23, column: 35
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'file:///data/data/io.neocles.dev/files/app/main.js', line: 6, column: 20
    Frame: function:'require', file:'', line: 1, column: 266
```

By including all of rxjs, immediate.js gets included which assumes a document which doesn't exist in nativescript.
